import {Component, ElementRef, OnDestroy, OnInit, ViewChild} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import { ToastController } from '@ionic/angular';
import { ScreenOrientation } from '@ionic-native/screen-orientation/ngx';
import { AndroidFullScreen } from '@ionic-native/android-full-screen/ngx';
import {ModalController, NavController} from '@ionic/angular';
import {RouterPage} from '../../helpers/RouterPage';
import {QuizzesService} from '../../services/quizzes.service';
import {HandleService} from '../../services/handle.service';
import {LoadingPreference} from '../../preferences/LoadingPreference';
import AppParams from '../../params';
import {MainQuizComponent} from '../../modals/quizzes/main-quiz/main-quiz.component';
import {QuizStartConfirmationComponent} from '../../modals/quizzes/quiz-start-confirmation/quiz-start-confirmation.component';
import {TabsServices} from '../../services/tabs.services';

@Component({
  selector: 'app-quizzes',
  templateUrl: './quizzes.page.html',
  styleUrls: ['./quizzes.page.scss'],
})
export class QuizzesPage extends RouterPage implements OnInit, OnDestroy {

  autoGeneratedQuizzes: any[] = [];
  topQuizzes: any;
  monsterExplosionImage: string = null;
  appParams = AppParams;
  passedPosition: number = null;
  quizHoleImage = './assets/images/smoke.png';
  pageLoaded: boolean;
  @ViewChild('explosionAudio') explosionAudio: ElementRef<HTMLAudioElement>;

  constructor(
      public toastController: ToastController,
      private screenOrientation: ScreenOrientation,
      private quizzesService: QuizzesService,
      private loadingPref: LoadingPreference,
      private androidFullScreen: AndroidFullScreen,
      private router: Router,
      public modalController: ModalController,
      private navCtrl: NavController,
      private route: ActivatedRoute,
      private handler: HandleService,
      public tabsService: TabsServices,
      public elementRef: ElementRef
  ) {
    super(router, route);
    this.route.params.subscribe((params) => {
        this.passedPosition = params.passedPosition ? +params.passedPosition : null;
    });
  }

  async onEnter() {
    this.pageLoaded = false;
    const loading = await this.loadingPref.make();
    loading.present();

    await this.getAllQuizzes();
    loading.dismiss();

    this.pageLoaded = true;
    this.explosionMonster();
  }

  explosionMonster() {
    if (this.passedPosition != null) {
      const elements = this.elementRef.nativeElement.querySelectorAll('.monster-explosion');
      const element = elements[this.passedPosition];
      element.classList.add('explosion');
      this.explosionAudio.nativeElement.onended = () => this.stopExplosionAudio();
      this.explosionAudio.nativeElement.play();
    }
  }

  ngOnInit() {
  }

  getAllQuizzes() {
    return new Promise((resolve, reject) => {
      let loading = 1;
      this.handler.run(this.quizzesService.getFundamentals())
          .then((res: any) => {
            this.autoGeneratedQuizzes = res.fundamentalsAutogenerated;
            if (loading < 3) {
              loading++;
            } else {
              resolve();
            }
          })
          .catch((err) => {
            this.handler.presentAlert(err.error.message, err);
          });

      this.handler.run(this.quizzesService.getTopQuizzes())
          .then((res: any) => {
            this.topQuizzes = res;
            if (loading < 3) {
              loading++;
            } else {
              resolve();
            }
          })
          .catch((err) => {
            this.handler.presentAlert(err.error.message, err);
          });

      this.handler.run(this.quizzesService.getMonsterExplosionImage())
          .then((res: any) => {
            this.monsterExplosionImage = this.appParams.makeStaticUrl(res.image);
            if (loading < 3) {
              loading++;
            } else {
              resolve();
            }
          })
          .catch((err) => {
            this.handler.presentAlert(err.error.message, err);
          });
    });
  }

  async goToQuiz(quizId: string, position: number = null) {
    try {
      const modal = await this.modalController.create({
        component: MainQuizComponent,
        componentProps: {quizId, passedPosition: position}
      });
      return await modal.present();
    } catch (e) {
      this.handler.presentAlert(e.error.message, e);
    }
  }

  async openTopQuiz(quiz) {
    if (quiz.passed) {
      const toast = await this.toastController.create({
        message: 'This quiz is not available yet.',
        duration: 2000
      });
      return toast.present();
    }

    return this.quizStartConfirmation(quiz.id, null);
  }

  async quizStartConfirmation(quizId: string, position: number = null) {
    this.stopExplosionAudio();
    position = 2 - ((this.autoGeneratedQuizzes.length - 1) - position);
    const loading = await this.loadingPref.make();
    loading.present();
    try {
      const quizStartData: any = await this.handler.run(this.quizzesService.getQuizStartData(quizId));
      const quizConfirmationModal = await this.modalController.create({
        component: QuizStartConfirmationComponent,
        componentProps: {
          quizData: quizStartData,
        }
      });
      quizConfirmationModal.onDidDismiss().then((accepted) => {
        if (accepted.data) {
          return this.goToQuiz(quizId, position);
        }
      });
      loading.dismiss();
      await quizConfirmationModal.present();
    } catch (e) {
      this.handler.presentAlert(e.error.message, e);
      loading.dismiss();
    }

  }

  makeMonsterHeight(aQuiz): string {
    const percentage = aQuiz.monster_height;
    const resultPercentage = 100 - (percentage / 5);

    if (percentage === 0 ) {
      return '100%';
    }

    if (resultPercentage < 30) {
      return '30%';
    }

    if (percentage === 100) {
      return '100%';
    }

    return  resultPercentage + '%';
  }

  async ionViewDidEnter() {
    this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE);
    this.tabsService.toggleTabsVisibility(false);
    try {
      await this.androidFullScreen.isImmersiveModeSupported();
      await this.androidFullScreen.immersiveMode();
    } catch (e) {
      console.log('No full screen');
    }

  }

  smokeCounter() {
    return new Array(3 - this.autoGeneratedQuizzes.length);
  }

  async ionViewWillLeave() {
    this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE);
    this.stopExplosionAudio();
    this.tabsService.toggleTabsVisibility(true);
    this.screenOrientation.unlock();
    try {
      await this.androidFullScreen.isImmersiveModeSupported();
      await this.androidFullScreen.showSystemUI();
    } catch (e) {
      console.log('No full screen');
    }
  }

    ionViewDidLeave() {
      this.passedPosition = null;
    }

  private stopExplosionAudio() {
    const element = this.elementRef.nativeElement.querySelector('.explosion');
    if (element) {
      element.classList.remove('explosion');
    }
    this.passedPosition = null;
    this.explosionAudio.nativeElement.pause();
  }

  ngOnDestroy(): void {
    super.ngOnDestroy();
  }

}
